sudo: required
services:
  - docker
before_install:
  - docker pull node:8-onbuild
script:
  - docker run --rm probot-hello  npm run test
  - docker run --rm probot-hello  npm run lint
install:
  - docker build -t probot-hello .
deploy:
  provider: heroku
  on: heroku_production
  app: probot-hikmat-app
  api-key:
    secure: FVegfwHEmJhJsZ1MYzbBrCLW51fh8iyFAUfvzLGjRUTj9JQT+t4Up/po52v7m8coDw3aXD6ThWfzpw6Klv51OS+Q8f9/S2Gyd4Ilf5xVzROkvEa5LyNVGjWrhRsh01f89joAEOTtk+Xepon9NC5Glu/xW1rkimEN0jCJG+EFzDCmr4ygLsgWXjw+Zm0MpIGZJOyZ4yT0+Yp9nMfjivQ8UVoago5U//BtZDteT1i3j6FC4jBcYbIytdk8lzzdGBkRuaoGCZ6Qgp0GLiSUWHXgXDC3oR+BDUPm5RDA0oFH60d9lmWIptm5hL2oCwuiXe3bw6QzeKVDeW+w3ihv4Zckzd68yoyffpZaJ16iQGJep828SpOUG86A6xkhVTUOSfsXA3i6Nxp5oENzO36vyVJx1Fjm3vj/m0fFbiqda47DRcZMyvxub4XL26xHt92RZLuBbHNm/rnJ7RqSfTkS5RKf+R30YY7e85rC4x6WdsgGXgNtRgbKpm9zla/E/StEqWonIbNP7/B8XFqVBcQ9cq1sV744WmrykJAii7FVVQqzY07hZn9YGpudapTSylCse6XjpGnfshqnitOZKO12299sE7rR7A9PH9FSaSkU3IBluYXU3z/miEY72ia8k7hFcDn2649+eq2p69D4oHt8QCMMFjeU7uk62wrfVGhu/ylFp5g=
