sudo: required
services:
  - docker
before_install:
  - docker pull node:8-onbuild
script:
  - docker run --rm probot-hello  npm run test
  - docker run --rm probot-hello  npm run lint
install:
  - docker build -t probot-hello .
deploy:
  provider: heroku
  on: heroku_production
  app: probot-hikmat-app
  api-key:
    secure: MIIEowIBAAKCAQEAyuH3IsfrTYaUo+DCjvxoustKUoBDiLXaeDSK6DJaKYxWGdojG82LW73bfmmNaaol/g/IAOrLQlrOz6aTmPKufss18SRCTOnvnvgg5aAiUDifJFW8+6byjqCCN7xDImqPVgyuBtcFmyvh9eu04ud4cXksttS/xGxqn4jLpUIQQBfrQeZbfIX/kuhxnnWOiVtNeliZ7p11XxAyakMThWthPRKFeRZTJlqEBKkVxzGYRJzCwkW3tdH4qKZPw+uaERl2ObZx6iI199VFRdZf6FanuD4FrPZgV8Jm/v96sfYriQqW87L5ZQv0EcbuFvoXyR6fXyT72iSx+w9n8xcgOvK9SwIDAQABAoIBAQC1XIRI8kAVQH41dOFXYqnYeYwJ7iDw3+fZVtbptMFGrO33FDoYS4kNTM4e1gqU74Yg9EiNEVb8DSMdG0KMEj0MmWmyFAC0stcC27rEqn6iCcuxdneG2nmwKCnf2wqEhI93k8Qp1yNq0DKhXMCJqfPQNEtVcR+wXl5+GJI7O7A9KczMAko/izrj+1WqHIkSkJWX5RlO4G9tgkq/HQdw3wuaBlyj76kCUG4fZOozow4cv6A9FjYPlcdMPqvDyo+JWQROKkFIM6iJu4z549C7WgFoiGHCW0lFNc5JBk/6MDBbjtbOetPiOEqx461r1kfLEqduvIv3yP7kYZ+aEvLsfPUZAoGBAO4Lz+rFZHOcXcnwHUHdZtekpuirfN89BSYd2cNJeKyPodlMec686ufeOqmWsYOwRQzWJKG5Xd0ai7/MVpFj7ZL6XB4GXlCWy7RDH6/T9wr3pU7Mg2DAZu+uj36SHe7EXN+PEqd2tACMn+uQnsUvVyAAcPlVRH0c4ocfG3hODdmfAoGBANovN9QEmGfTFbE4+S/4j91CcLa80hrfR4l1ZV15kDgOos2uEl5ps1sukU2w1n0CA9V8ciyS+T2Jzdj4UbineI0yuwuMCN1LGdqJtm+fAiLmfd2TfVEjA1/uvbNHa6XAe5gXZJ+sKLXpIUMntJ6WrMHL9HklkEtkYnW1yBAMq9TVAoGAd2ynp+HV7oZhK0FyfCvGP6OUNSBrqlejsKbDLE085F2+1hSe+5AdzavZBGHctvOFANaiVBx6McXynIu4VoKqmtVNx6ZsRMQSeGJAkGaoBvGNFoZV1wFP4ylRRi+qIrKS4XmW4zsTPT9Pr8/DR6vjauOtyfj0PkxyfVWm42lNW4MCgYBVHSJsRTanGgNWVWFwQ0jsCaUqxFI6RWwExZU7d9a454y/K+7igd2D7pCkfB3QOl8Ag0GO/e7ZAM8amxRWMo6mlmm9QW2b1lZJmHtg4+jTcJMdQxIZ+sywOdQrAeuOh54vYMDSQTjIbh+ZsP2W+DSAjW3bbLnzjz+Rp85Z5HeL2QKBgBhfcg3cxSys3U9S4WX3rnXZ/KKPKO67es8suCXJd5yTMnzPX++WTYGlmQmhECkuFybWhxOicrr+eiWID1zf4Z9a4I7V9T8YGudg0ntQgmHvjKGs2rKEEG+Y1ueFRqIKFzTTyWB7KnKBV0xtZGEaSaU6W10s2EaDCpdwbufvi919
